# 服务器基础配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "dev"               #dev/test/prod 区分环境

# 日志配置
log:
  level: "info"             #debug/info/warn/error
  path: "./logs/agent.log"  #日志存储路径
  max_size: 100             # 单个日志文件最大大小（MB）
  max_backups: 7             # 保留日志文件数

# AI配置
ai:
  model: "qwen-turbo"
  timeout: 30
  max_retries: 3

# redis数据库配置
redis:
  addr: "localhost:6379"
  password: ""
  db: 0

rate_limit:
  max_requests: 10 #每秒最多10次请求